### ISSUE TITLE
Watch in specific namespace

### ISSUE THREAD

**Issue by allamand** [admiraltyio/multicluster-controller#2]
Hello,

I'm trying to understand how multicluster-controller works and I would like to to configure a Watch to a specific namespace. I tried to update this part specifiying a namespace:

```
	p := v1.Pod{
		TypeMeta: metav1.TypeMeta{
			Kind:       "Pod",
			APIVersion: "v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Namespace: namespace,
		},
	}
	if err := co.WatchResourceReconcileObject(cluster1, &p, controller.WatchOptions{}); err != nil {
		return nil, fmt.Errorf("setting up Pod watch in cluster1 cluster: %v", err)
	}
```

But at runtime, the watch show me all pods cluster-wide..

How can I configure it to watch a namespace correctly ?

thanks

sébastien

**Comment by adrienjt** [comment]
[v0.2.0](https://github.com/admiraltyio/multicluster-controller/releases/tag/v0.2.0) adds watch options.

In your case, you'd fill in the new [Namespace](https://github.com/admiraltyio/multicluster-controller/blob/0bb36bce5c3e2ae9dac56791693eabe069cda382/pkg/controller/controller.go#L97) field in WatchOptions.
